# Generated by Django 6.0.5 on 2026-05-20 14:04

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CopyrightTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(db_index=True, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Legislation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["reference", "url"],
            },
        ),
        migrations.CreateModel(
            name="RecordCopyrightTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copyright_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_copyright_titles",
                        to="store.copyrighttitle",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "copyright_title"],
            },
        ),
        migrations.CreateModel(
            name="RecordOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=255, unique=True)),
                ("ia_id", models.CharField(db_index=True, max_length=255)),
                ("reference", models.CharField(db_index=True, max_length=255)),
                ("title", models.TextField(blank=True, null=True)),
                ("translated_title", models.TextField(blank=True, null=True)),
                ("public_title", models.TextField(blank=True, null=True)),
                ("curated_title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("public_description", models.TextField(blank=True, null=True)),
                ("former_reference_tna", models.TextField(blank=True, null=True)),
                (
                    "former_reference_department",
                    models.TextField(blank=True, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("tag", models.TextField(blank=True, null=True)),
                ("arrangement", models.TextField(blank=True, null=True)),
                ("public_arrangement", models.TextField(blank=True, null=True)),
                (
                    "tdr_consignment_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "tdr_file_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "tdr_parent_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "tdr_uuid",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "dri_batch_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("source_internal_name", models.TextField(blank=True, null=True)),
                ("connected_asset_note", models.TextField(blank=True, null=True)),
                ("physical_description", models.TextField(blank=True, null=True)),
                (
                    "paper_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poor_law_union_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usage_restriction_description",
                    models.TextField(blank=True, null=True),
                ),
                ("uk_government_web_archive", models.URLField(blank=True, null=True)),
                (
                    "legal_status",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "held_by",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "transferred_by",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "date_last_modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "curated_modified_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "curated_date_start",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "curated_date_end",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("curated_modified_at_note", models.TextField(blank=True, null=True)),
                ("geographical_place", models.TextField(blank=True, null=True)),
                (
                    "covering_date_start",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "covering_date_end",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "provided_covering_date_start",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provided_covering_date_end",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provided_covering_date_text",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "film_production_company_name",
                    models.TextField(blank=True, null=True),
                ),
                ("film_title", models.TextField(blank=True, null=True)),
                ("film_duration", models.DurationField(blank=True, null=True)),
                ("evidence_provider", models.TextField(blank=True, null=True)),
                (
                    "investigations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "inquiry_hearing_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "inquiry_session_description",
                    models.TextField(blank=True, null=True),
                ),
                ("court_session", models.TextField(blank=True, null=True)),
                (
                    "court_session_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("seal_owner_name", models.TextField(blank=True, null=True)),
                (
                    "seal_colour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_attachment_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "seal_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image_sequence_end",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image_sequence_start",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("dimension_text", models.TextField(blank=True, null=True)),
                (
                    "seal_start_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seal_end_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seal_obverse_start_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seal_obverse_end_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seal_reverse_start_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seal_reverse_end_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("given_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "family_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birth_address", models.TextField(blank=True, null=True)),
                (
                    "national_registration_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "seaman_service_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "battalion_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_of_kin_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_of_kin_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "is_veteran",
                    models.BooleanField(blank=True, db_index=True, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "physical_condition_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "reference_google_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "reference_parent_google_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("archivist_note", models.TextField(blank=True, null=True)),
                (
                    "archivist_note_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("digital_file_count", models.PositiveIntegerField(default=0)),
                (
                    "copyright_titles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="records",
                        through="store.RecordCopyrightTitle",
                        to="store.copyrighttitle",
                    ),
                ),
            ],
            options={
                "ordering": ["reference", "record_id"],
            },
        ),
        migrations.AddField(
            model_name="recordcopyrighttitle",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record_copyright_titles",
                to="store.recordoutput",
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "family_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "alternative_given_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "alternative_family_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("birth_address", models.TextField(blank=True, null=True)),
                ("parish", models.CharField(blank=True, max_length=255, null=True)),
                ("town", models.CharField(blank=True, max_length=255, null=True)),
                ("county", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("age", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "national_registration_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "seaman_service_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "battalion_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "navy_division_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_of_kin_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "next_of_kin_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "is_veteran",
                    models.BooleanField(blank=True, db_index=True, null=True),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "family_name", "given_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="InquiryAppearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "witness_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                    ),
                ),
                ("appearance_description", models.TextField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_appearances",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("obverse", "Obverse"),
                            ("reverse", "Reverse"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "first",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "second",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_fragment", models.BooleanField(default=False)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "dimension_type"],
            },
        ),
        migrations.CreateModel(
            name="CourtCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("summary_judgment", models.TextField(blank=True, null=True)),
                (
                    "summary_reasons_for_judgment",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "hearing_start_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "hearing_end_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="court_cases",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_base64", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "timestamp", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecordRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("RedactionOf", "RedactionOf"),
                            ("HasRedaction", "HasRedaction"),
                            ("SeparatedMaterial", "SeparatedMaterial"),
                            ("RelatedMaterial", "RelatedMaterial"),
                            ("ReplacementOf", "ReplacementOf"),
                            ("HasReplacement", "HasReplacement"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "relationship", "reference", "id"],
            },
        ),
        migrations.CreateModel(
            name="SensitivityReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_sensitive_metadata",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("foi_asserted_date", models.DateField(blank=True, null=True)),
                ("sensitive_description", models.TextField(blank=True, null=True)),
                (
                    "access_condition_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "access_condition_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("closure_review_date", models.DateField(blank=True, null=True)),
                ("closure_start_date", models.DateField(blank=True, null=True)),
                ("closure_period", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "closure_end_year",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "instrument_number",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("instrument_signed_date", models.DateField(blank=True, null=True)),
                ("retention_reconsider_date", models.DateField(blank=True, null=True)),
                (
                    "ground_for_retention_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "ground_for_retention_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "sensitive_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("closure_description", models.TextField(blank=True, null=True)),
                (
                    "foi_exemptions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sensitivity_reviews",
                        to="store.legislation",
                    ),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitivity",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record"],
            },
        ),
        migrations.CreateModel(
            name="SensitivityReviewDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foi_asserted_date", models.JSONField(blank=True, null=True)),
                ("sensitive_name", models.JSONField(blank=True, null=True)),
                ("sensitive_description", models.JSONField(blank=True, null=True)),
                ("access_condition_name", models.JSONField(blank=True, null=True)),
                ("access_condition_code", models.JSONField(blank=True, null=True)),
                ("closure_review_date", models.JSONField(blank=True, null=True)),
                ("closure_start_date", models.JSONField(blank=True, null=True)),
                ("closure_period", models.JSONField(blank=True, null=True)),
                ("closure_end_year", models.JSONField(blank=True, null=True)),
                ("closure_description", models.JSONField(blank=True, null=True)),
                ("foi_exemptions", models.JSONField(blank=True, null=True)),
                ("instrument_number", models.JSONField(blank=True, null=True)),
                ("instrument_signed_date", models.JSONField(blank=True, null=True)),
                ("retention_reconsider_date", models.JSONField(blank=True, null=True)),
                ("ground_for_retention_code", models.JSONField(blank=True, null=True)),
                (
                    "ground_for_retention_description",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "change",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitivity",
                        to="store.change",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(db_index=True, max_length=255)),
                ("file_name", models.CharField(db_index=True, max_length=500)),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sort_order",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sequence",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("file_path", models.TextField(blank=True, null=True)),
                (
                    "scanner_operator_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scanner_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scanner_geographical_place",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scanned_image_crop",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scanned_image_deskew",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "scanned_image_split",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_files",
                        to="store.recordoutput",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "sort_order", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="Checksum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checksums",
                        to="store.variation",
                    ),
                ),
            ],
            options={
                "ordering": ["variation", "hash", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="recordoutput",
            index=models.Index(
                fields=["reference", "record_id"], name="store_recor_referen_637c3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordoutput",
            index=models.Index(
                fields=["record_type", "reference"],
                name="store_recor_record__f11ef4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recordoutput",
            index=models.Index(
                fields=["held_by", "reference"], name="store_recor_held_by_3a2ef8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordcopyrighttitle",
            index=models.Index(
                fields=["record", "copyright_title"],
                name="store_recor_record__d5f224_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recordcopyrighttitle",
            index=models.Index(
                fields=["copyright_title", "record"],
                name="store_recor_copyrig_976327_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recordcopyrighttitle",
            constraint=models.UniqueConstraint(
                fields=("record", "copyright_title"),
                name="unique_copyright_title_per_record",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["record", "family_name", "given_name"],
                name="store_perso_record__2ca8a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["record", "full_name"], name="store_perso_record__0f9f65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiryappearance",
            index=models.Index(
                fields=["record", "sequence"], name="store_inqui_record__ea3ef9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dimension",
            constraint=models.UniqueConstraint(
                fields=("record", "dimension_type"),
                name="unique_dimension_type_per_record",
            ),
        ),
        migrations.AddIndex(
            model_name="courtcase",
            index=models.Index(
                fields=["record", "sequence"], name="store_court_record__b43890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courtcase",
            index=models.Index(
                fields=["reference", "hearing_start_date"],
                name="store_court_referen_099f8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                fields=["record", "timestamp"], name="store_chang_record__6d971d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordrelationship",
            index=models.Index(
                fields=["record", "relationship"], name="store_recor_record__0ffcea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recordrelationship",
            index=models.Index(
                fields=["reference", "relationship"],
                name="store_recor_referen_f1e34e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variation",
            index=models.Index(
                fields=["record", "sort_order"], name="store_varia_record__95579e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variation",
            index=models.Index(
                fields=["record", "sequence"], name="store_varia_record__3a0915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variation",
            index=models.Index(
                fields=["file_id", "record"], name="store_varia_file_id_1af2d8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="variation",
            constraint=models.UniqueConstraint(
                fields=("record", "file_id"), name="unique_file_id_per_record"
            ),
        ),
        migrations.AddIndex(
            model_name="checksum",
            index=models.Index(
                fields=["variation", "hash"], name="store_check_variati_a5949b_idx"
            ),
        ),
    ]
