# Generated by Django 6.0.5 on 2026-05-29 14:11

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("catalogue_reference", models.TextField(blank=True, null=True)),
                ("type", models.TextField()),
                ("is_mastered", models.BooleanField(blank=True, null=True)),
                ("master_source", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField()),
                ("to_label", models.CharField()),
                ("from_label", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Relationships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributes", models.JSONField(blank=True, null=True)),
                (
                    "from_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.metadata",
                    ),
                ),
                (
                    "to_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.metadata",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.relationshiptypes",
                    ),
                ),
            ],
        ),
    ]
