name: Deploy

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - intg
          - prod
        default: 'intg'
permissions:
  id-token: write
  contents: read
env:
  ENVIRONMENT: ${{ inputs.environment || 'intg' }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'intg' }}
    env:
      AWS_REGION: eu-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy static files
        run: |
          docker compose up -d --build
          docker compose exec app tna-build
          mkdir -p site
          cd node_modules/@nationalarchives/frontend/nationalarchives
          cp all.js all.js.map favicon.ico fa-solid-900.woff2 all.css font-awesome.css print.css ie.css ../../../../site
          cd ../../../../site
          aws s3 sync . s3://$ENVIRONMENT-metadata-store-static-files-$ACCOUNT_NUMBER-eu-west-2-an/static/
          aws lambda invoke --function-name $ENVIRONMENT-data-migration --cli-binary-format raw-in-base64-out --payload {}  out
        env:
          ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      - name: Build migrate lambda
        run: |
          python3 -m pip install --user pipx
          pipx install poetry
          poetry install --with dev
          poetry run zappa package dev -o terraform/metadata-store.zip
          
          mkdir -p package
          pip install --target=package .
          pip install --target=package requests
          cd package
          zip -rA ../migrate.zip .
          cd ..
          zip -rA migrate.zip store
          zip -rA migrate.zip tests/test_scripts
          zip migrate.zip migrate.py
          mv migrate.zip terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform apply
        working-directory: terraform
        run: |
          terraform init
          terraform workspace select $ENVIRONMENT
          terraform apply -auto-approve -var-file $ENVIRONMENT.auto.tfvars
        env:
          TF_VAR_app_secret: ${{ secrets.APP_SECRET }}
          TF_VAR_saml_tenant: ${{ secrets.SAML_TENANT }}
          TF_VAR_entra_app_id: ${{ secrets.ENTRA_APP_ID }}

        
