name: Test
on: push

permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: |
          echo "127.0.0.1 oidc" | sudo tee -a /etc/hosts
          docker compose up -d --build
          docker compose exec app poetry run python /app/manage.py migrate
          docker compose exec app poetry run python /app/manage.py loaddata change_reason
          docker compose exec app poetry run python /app/manage.py loaddata /app/tests/test_scripts/test-fixture.json
          timeout 60 bash -c 'while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ | grep -q "^302$"; do sleep 1; done'
          docker compose exec app poetry run python /app/manage.py test store.tests
          docker compose exec app poetry run ruff format --check
      - run: |
          npm install
          npm t
        working-directory: tests/e2e
        env:
          USER: user1
          PASSWORD: password
          TOKEN_ENDPOINT: http://oidc/token
          CLIENT_ID: demo-client CLIENT_SECRET=demo-secret
          CYPRESS_BASE_URL: http://localhost:8000
